# Generated by Django 3.2.21 on 2023-09-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20230923_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actress',
            name='info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='info',
            field=models.TextField(null=True),
        ),
    ]
